const g_awtk_assets = {
  image: [
    {name:"pointer_4", uri:"/assets/raw/images/svg/pointer_4.bsvg"},
    {name:"pointer", uri:"/assets/raw/images/svg/pointer.svg"},
    {name:"girl", uri:"/assets/raw/images/svg/girl.svg"},
    {name:"china", uri:"/assets/raw/images/svg/china.bsvg"},
    {name:"china", uri:"/assets/raw/images/svg/china.svg"},
    {name:"pointer_4", uri:"/assets/raw/images/svg/pointer_4.svg"},
    {name:"pointer_1", uri:"/assets/raw/images/svg/pointer_1.svg"},
    {name:"pointer_1", uri:"/assets/raw/images/svg/pointer_1.bsvg"},
    {name:"pointer", uri:"/assets/raw/images/svg/pointer.bsvg"},
    {name:"girl", uri:"/assets/raw/images/svg/girl.bsvg"},
    {name:"info", uri:"/assets/raw/images/x1/info.png", w:24, h:24},
    {name:"me", uri:"/assets/raw/images/x1/me.png", w:24, h:24},
    {name:"middle_off", uri:"/assets/raw/images/x1/middle_off.png", w:24, h:24},
    {name:"red_btn_p", uri:"/assets/raw/images/x1/red_btn_p.png", w:30, h:30},
    {name:"check", uri:"/assets/raw/images/x1/check.png", w:24, h:24},
    {name:"cursor", uri:"/assets/raw/images/x1/cursor.png", w:16, h:16},
    {name:"green_btn_n", uri:"/assets/raw/images/x1/green_btn_n.png", w:30, h:30},
    {name:"muted", uri:"/assets/raw/images/x1/muted.png", w:24, h:24},
    {name:"num_dot", uri:"/assets/raw/images/x1/num_dot.jpg", w:16, h:48},
    {name:"arrow_down_o", uri:"/assets/raw/images/x1/arrow_down_o.png", w:24, h:24},
    {name:"rgb", uri:"/assets/raw/images/x1/rgb.png", w:30, h:30},
    {name:"arrow_down_n", uri:"/assets/raw/images/x1/arrow_down_n.png", w:24, h:24},
    {name:"green_btn_o", uri:"/assets/raw/images/x1/green_btn_o.png", w:30, h:30},
    {name:"msg_active", uri:"/assets/raw/images/x1/msg_active.png", w:24, h:24},
    {name:"play_n", uri:"/assets/raw/images/x1/play_n.png", w:24, h:24},
    {name:"radio_checked", uri:"/assets/raw/images/x1/radio_checked.png", w:24, h:24},
    {name:"middle_on", uri:"/assets/raw/images/x1/middle_on.png", w:24, h:24},
    {name:"msg", uri:"/assets/raw/images/x1/msg.png", w:24, h:24},
    {name:"play_o", uri:"/assets/raw/images/x1/play_o.png", w:24, h:24},
    {name:"bricks", uri:"/assets/raw/images/x1/bricks.png", w:60, h:60},
    {name:"shifton", uri:"/assets/raw/images/x1/shifton.png", w:16, h:16},
    {name:"active_dot", uri:"/assets/raw/images/x1/active_dot.png", w:10, h:10},
    {name:"question", uri:"/assets/raw/images/x1/question.png", w:24, h:24},
    {name:"zh", uri:"/assets/raw/images/x1/zh.png", w:24, h:24},
    {name:"discovery_active", uri:"/assets/raw/images/x1/discovery_active.png", w:24, h:24},
    {name:"dot", uri:"/assets/raw/images/x1/dot.png", w:10, h:10},
    {name:"rgba", uri:"/assets/raw/images/x1/rgba.png", w:30, h:30},
    {name:"empty", uri:"/assets/raw/images/x1/empty.png", w:24, h:24},
    {name:"battery_0", uri:"/assets/raw/images/x1/battery_0.png", w:57, h:32},
    {name:"num_0", uri:"/assets/raw/images/x1/num_0.jpg", w:30, h:48},
    {name:"slider_v_fg", uri:"/assets/raw/images/x1/slider_v_fg.png", w:8, h:30},
    {name:"ani1", uri:"/assets/raw/images/x1/ani1.png", w:70, h:70},
    {name:"visible", uri:"/assets/raw/images/x1/visible.png", w:16, h:16},
    {name:"edit_clear_p", uri:"/assets/raw/images/x1/edit_clear_p.png", w:24, h:24},
    {name:"arrow_up_o", uri:"/assets/raw/images/x1/arrow_up_o.png", w:24, h:24},
    {name:"arrow_up_n", uri:"/assets/raw/images/x1/arrow_up_n.png", w:24, h:24},
    {name:"left_on", uri:"/assets/raw/images/x1/left_on.png", w:24, h:24},
    {name:"num_1", uri:"/assets/raw/images/x1/num_1.jpg", w:30, h:48},
    {name:"battery_1", uri:"/assets/raw/images/x1/battery_1.png", w:57, h:32},
    {name:"arrow_right_p", uri:"/assets/raw/images/x1/arrow_right_p.png", w:24, h:24},
    {name:"battery_3", uri:"/assets/raw/images/x1/battery_3.png", w:57, h:32},
    {name:"num_3", uri:"/assets/raw/images/x1/num_3.jpg", w:30, h:48},
    {name:"slider_drag_o", uri:"/assets/raw/images/x1/slider_drag_o.png", w:28, h:28},
    {name:"guage_bg", uri:"/assets/raw/images/x1/guage_bg.jpg", w:240, h:240},
    {name:"en", uri:"/assets/raw/images/x1/en.png", w:24, h:24},
    {name:"ani2", uri:"/assets/raw/images/x1/ani2.png", w:70, h:70},
    {name:"arrow_left_n", uri:"/assets/raw/images/x1/arrow_left_n.png", w:24, h:24},
    {name:"clock_second", uri:"/assets/raw/images/x1/clock_second.png", w:2, h:180},
    {name:"arrow_left_o", uri:"/assets/raw/images/x1/arrow_left_o.png", w:24, h:24},
    {name:"ani3", uri:"/assets/raw/images/x1/ani3.png", w:70, h:70},
    {name:"num_2", uri:"/assets/raw/images/x1/num_2.jpg", w:30, h:48},
    {name:"battery_2", uri:"/assets/raw/images/x1/battery_2.png", w:57, h:32},
    {name:"num_6", uri:"/assets/raw/images/x1/num_6.jpg", w:30, h:48},
    {name:"ania", uri:"/assets/raw/images/x1/ania.png", w:70, h:70},
    {name:"ani7", uri:"/assets/raw/images/x1/ani7.png", w:70, h:70},
    {name:"shift", uri:"/assets/raw/images/x1/shift.png", w:16, h:16},
    {name:"ani6", uri:"/assets/raw/images/x1/ani6.png", w:70, h:70},
    {name:"close_p", uri:"/assets/raw/images/x1/close_p.png", w:24, h:24},
    {name:"num_7", uri:"/assets/raw/images/x1/num_7.jpg", w:30, h:48},
    {name:"checked", uri:"/assets/raw/images/x1/checked.png", w:24, h:24},
    {name:"battery_5", uri:"/assets/raw/images/x1/battery_5.png", w:57, h:32},
    {name:"num_5", uri:"/assets/raw/images/x1/num_5.jpg", w:30, h:48},
    {name:"anib", uri:"/assets/raw/images/x1/anib.png", w:70, h:70},
    {name:"ani4", uri:"/assets/raw/images/x1/ani4.png", w:70, h:70},
    {name:"me_active", uri:"/assets/raw/images/x1/me_active.png", w:24, h:24},
    {name:"ani5", uri:"/assets/raw/images/x1/ani5.png", w:70, h:70},
    {name:"anic", uri:"/assets/raw/images/x1/anic.png", w:70, h:70},
    {name:"earth", uri:"/assets/raw/images/x1/earth.png", w:24, h:24},
    {name:"contact_active", uri:"/assets/raw/images/x1/contact_active.png", w:24, h:24},
    {name:"dialog_title", uri:"/assets/raw/images/x1/dialog_title.png", w:60, h:30},
    {name:"num_4", uri:"/assets/raw/images/x1/num_4.jpg", w:30, h:48},
    {name:"close_d", uri:"/assets/raw/images/x1/close_d.png", w:24, h:24},
    {name:"battery_4", uri:"/assets/raw/images/x1/battery_4.png", w:57, h:32},
    {name:"contact", uri:"/assets/raw/images/x1/contact.png", w:24, h:24},
    {name:"slider_fg", uri:"/assets/raw/images/x1/slider_fg.png", w:30, h:8},
    {name:"arrow_right_o", uri:"/assets/raw/images/x1/arrow_right_o.png", w:24, h:24},
    {name:"num_9", uri:"/assets/raw/images/x1/num_9.jpg", w:30, h:48},
    {name:"ani8", uri:"/assets/raw/images/x1/ani8.png", w:70, h:70},
    {name:"edit_clear_n", uri:"/assets/raw/images/x1/edit_clear_n.png", w:24, h:24},
    {name:"arrow_up_p", uri:"/assets/raw/images/x1/arrow_up_p.png", w:24, h:24},
    {name:"edit_clear_o", uri:"/assets/raw/images/x1/edit_clear_o.png", w:24, h:24},
    {name:"ani9", uri:"/assets/raw/images/x1/ani9.png", w:70, h:70},
    {name:"find", uri:"/assets/raw/images/x1/find.png", w:24, h:24},
    {name:"discovery", uri:"/assets/raw/images/x1/discovery.png", w:24, h:24},
    {name:"num_8", uri:"/assets/raw/images/x1/num_8.jpg", w:30, h:48},
    {name:"arrow_right_n", uri:"/assets/raw/images/x1/arrow_right_n.png", w:24, h:24},
    {name:"backspace", uri:"/assets/raw/images/x1/backspace.png", w:16, h:16},
    {name:"arrow_left_p", uri:"/assets/raw/images/x1/arrow_left_p.png", w:24, h:24},
    {name:"clock_hour", uri:"/assets/raw/images/x1/clock_hour.png", w:20, h:82},
    {name:"slider_drag_p", uri:"/assets/raw/images/x1/slider_drag_p.png", w:28, h:28},
    {name:"logo", uri:"/assets/raw/images/x1/logo.png", w:148, h:68},
    {name:"invisible", uri:"/assets/raw/images/x1/invisible.png", w:16, h:16},
    {name:"close_o", uri:"/assets/raw/images/x1/close_o.png", w:24, h:24},
    {name:"clock_bg", uri:"/assets/raw/images/x1/clock_bg.jpg", w:300, h:300},
    {name:"cross", uri:"/assets/raw/images/x1/cross.png", w:32, h:32},
    {name:"clock_minute", uri:"/assets/raw/images/x1/clock_minute.png", w:12, h:135},
    {name:"radio_unchecked", uri:"/assets/raw/images/x1/radio_unchecked.png", w:24, h:24},
    {name:"switch", uri:"/assets/raw/images/x1/switch.png", w:90, h:22},
    {name:"close_n", uri:"/assets/raw/images/x1/close_n.png", w:24, h:24},
    {name:"clock", uri:"/assets/raw/images/x1/clock.png", w:42, h:42},
    {name:"unchecked", uri:"/assets/raw/images/x1/unchecked.png", w:24, h:24},
    {name:"red_btn_n", uri:"/assets/raw/images/x1/red_btn_n.png", w:30, h:30},
    {name:"slider_drag", uri:"/assets/raw/images/x1/slider_drag.png", w:28, h:28},
    {name:"red_btn_o", uri:"/assets/raw/images/x1/red_btn_o.png", w:30, h:30},
    {name:"green_btn_p", uri:"/assets/raw/images/x1/green_btn_p.png", w:30, h:30},
    {name:"arrow_down_p", uri:"/assets/raw/images/x1/arrow_down_p.png", w:24, h:24},
    {name:"warn", uri:"/assets/raw/images/x1/warn.png", w:24, h:24},
    {name:"slider_v_bg", uri:"/assets/raw/images/x1/slider_v_bg.png", w:8, h:30},
    {name:"right_on", uri:"/assets/raw/images/x1/right_on.png", w:24, h:24},
    {name:"2", uri:"/assets/raw/images/x1/2.jpg", w:100, h:73},
    {name:"slider_bg", uri:"/assets/raw/images/x1/slider_bg.png", w:30, h:8},
    {name:"guage_pointer", uri:"/assets/raw/images/x1/guage_pointer.png", w:24, h:144},
    {name:"play_p", uri:"/assets/raw/images/x1/play_p.png", w:24, h:24},
    {name:"unmuted", uri:"/assets/raw/images/x1/unmuted.png", w:24, h:24},
    {name:"right_off", uri:"/assets/raw/images/x1/right_off.png", w:24, h:24},
    {name:"message", uri:"/assets/raw/images/x1/message.png", w:24, h:24},
    {name:"3", uri:"/assets/raw/images/x1/3.jpg", w:100, h:73},
    {name:"1", uri:"/assets/raw/images/x1/1.jpg", w:128, h:128},
    {name:"progress_circle", uri:"/assets/raw/images/x1/progress_circle.png", w:100, h:100},
    {name:"bee", uri:"/assets/raw/images/x1/bee.gif", w:80, h:80},
    {name:"left_off", uri:"/assets/raw/images/x1/left_off.png", w:24, h:24},
    {name:"bg_landscape_1", uri:"/assets/raw/images/xx/bg_landscape_1.jpg", w:800, h:600},
    {name:"bg_landscape_2", uri:"/assets/raw/images/xx/bg_landscape_2.jpg", w:800, h:600},
    {name:"flag_none", uri:"/assets/raw/images/xx/flag_none.jpg", w:77, h:64},
    {name:"bg_landscape_3", uri:"/assets/raw/images/xx/bg_landscape_3.jpg", w:800, h:600},
    {name:"bg_portrait_1", uri:"/assets/raw/images/xx/bg_portrait_1.jpg", w:320, h:480},
    {name:"bg_portrait_2", uri:"/assets/raw/images/xx/bg_portrait_2.jpg", w:600, h:800},
    {name:"flag_CN", uri:"/assets/raw/images/xx/flag_CN.png", w:97, h:64},
    {name:"bg_portrait_3", uri:"/assets/raw/images/xx/bg_portrait_3.jpg", w:600, h:800},
    {name:"flag_US", uri:"/assets/raw/images/xx/flag_US.png", w:96, h:64},
    {name:"info", uri:"/assets/raw/images/x3/info.png", w:64, h:64},
    {name:"me", uri:"/assets/raw/images/x3/me.png", w:64, h:64},
    {name:"middle_off", uri:"/assets/raw/images/x3/middle_off.png", w:64, h:64},
    {name:"check", uri:"/assets/raw/images/x3/check.png", w:64, h:64},
    {name:"muted", uri:"/assets/raw/images/x3/muted.png", w:64, h:64},
    {name:"arrow_down_o", uri:"/assets/raw/images/x3/arrow_down_o.png", w:64, h:64},
    {name:"rgb", uri:"/assets/raw/images/x3/rgb.png", w:30, h:30},
    {name:"arrow_down_n", uri:"/assets/raw/images/x3/arrow_down_n.png", w:64, h:64},
    {name:"msg_active", uri:"/assets/raw/images/x3/msg_active.png", w:64, h:64},
    {name:"play_n", uri:"/assets/raw/images/x3/play_n.png", w:64, h:64},
    {name:"radio_checked", uri:"/assets/raw/images/x3/radio_checked.png", w:64, h:64},
    {name:"middle_on", uri:"/assets/raw/images/x3/middle_on.png", w:64, h:64},
    {name:"msg", uri:"/assets/raw/images/x3/msg.png", w:64, h:64},
    {name:"play_o", uri:"/assets/raw/images/x3/play_o.png", w:64, h:64},
    {name:"question", uri:"/assets/raw/images/x3/question.png", w:64, h:64},
    {name:"discovery_active", uri:"/assets/raw/images/x3/discovery_active.png", w:64, h:64},
    {name:"rgba", uri:"/assets/raw/images/x3/rgba.png", w:30, h:30},
    {name:"edit_clear_p", uri:"/assets/raw/images/x3/edit_clear_p.png", w:64, h:64},
    {name:"arrow_up_o", uri:"/assets/raw/images/x3/arrow_up_o.png", w:64, h:64},
    {name:"arrow_up_n", uri:"/assets/raw/images/x3/arrow_up_n.png", w:64, h:64},
    {name:"left_on", uri:"/assets/raw/images/x3/left_on.png", w:64, h:64},
    {name:"arrow_right_p", uri:"/assets/raw/images/x3/arrow_right_p.png", w:64, h:64},
    {name:"arrow_left_n", uri:"/assets/raw/images/x3/arrow_left_n.png", w:64, h:64},
    {name:"arrow_left_o", uri:"/assets/raw/images/x3/arrow_left_o.png", w:64, h:64},
    {name:"checked", uri:"/assets/raw/images/x3/checked.png", w:64, h:64},
    {name:"me_active", uri:"/assets/raw/images/x3/me_active.png", w:64, h:64},
    {name:"earth", uri:"/assets/raw/images/x3/earth.png", w:64, h:64},
    {name:"contact_active", uri:"/assets/raw/images/x3/contact_active.png", w:64, h:64},
    {name:"contact", uri:"/assets/raw/images/x3/contact.png", w:64, h:64},
    {name:"arrow_right_o", uri:"/assets/raw/images/x3/arrow_right_o.png", w:64, h:64},
    {name:"edit_clear_n", uri:"/assets/raw/images/x3/edit_clear_n.png", w:64, h:64},
    {name:"arrow_up_p", uri:"/assets/raw/images/x3/arrow_up_p.png", w:64, h:64},
    {name:"edit_clear_o", uri:"/assets/raw/images/x3/edit_clear_o.png", w:64, h:64},
    {name:"find", uri:"/assets/raw/images/x3/find.png", w:64, h:64},
    {name:"discovery", uri:"/assets/raw/images/x3/discovery.png", w:64, h:64},
    {name:"arrow_right_n", uri:"/assets/raw/images/x3/arrow_right_n.png", w:64, h:64},
    {name:"arrow_left_p", uri:"/assets/raw/images/x3/arrow_left_p.png", w:64, h:64},
    {name:"radio_unchecked", uri:"/assets/raw/images/x3/radio_unchecked.png", w:64, h:64},
    {name:"switch", uri:"/assets/raw/images/x3/switch.png", w:360, h:90},
    {name:"unchecked", uri:"/assets/raw/images/x3/unchecked.png", w:64, h:64},
    {name:"arrow_down_p", uri:"/assets/raw/images/x3/arrow_down_p.png", w:64, h:64},
    {name:"warn", uri:"/assets/raw/images/x3/warn.png", w:64, h:64},
    {name:"right_on", uri:"/assets/raw/images/x3/right_on.png", w:64, h:64},
    {name:"play_p", uri:"/assets/raw/images/x3/play_p.png", w:64, h:64},
    {name:"unmuted", uri:"/assets/raw/images/x3/unmuted.png", w:64, h:64},
    {name:"right_off", uri:"/assets/raw/images/x3/right_off.png", w:64, h:64},
    {name:"message", uri:"/assets/raw/images/x3/message.png", w:128, h:128},
    {name:"1", uri:"/assets/raw/images/x3/1.jpg", w:128, h:128},
    {name:"progress_circle", uri:"/assets/raw/images/x3/progress_circle.png", w:100, h:100},
    {name:"left_off", uri:"/assets/raw/images/x3/left_off.png", w:64, h:64},
    {name:"info", uri:"/assets/raw/images/x2/info.png", w:48, h:48},
    {name:"me", uri:"/assets/raw/images/x2/me.png", w:48, h:48},
    {name:"middle_off", uri:"/assets/raw/images/x2/middle_off.png", w:48, h:48},
    {name:"red_btn_p", uri:"/assets/raw/images/x2/red_btn_p.png", w:30, h:30},
    {name:"check", uri:"/assets/raw/images/x2/check.png", w:48, h:48},
    {name:"cursor", uri:"/assets/raw/images/x2/cursor.png", w:16, h:16},
    {name:"green_btn_n", uri:"/assets/raw/images/x2/green_btn_n.png", w:30, h:30},
    {name:"muted", uri:"/assets/raw/images/x2/muted.png", w:48, h:48},
    {name:"num_dot", uri:"/assets/raw/images/x2/num_dot.jpg", w:20, h:60},
    {name:"arrow_down_o", uri:"/assets/raw/images/x2/arrow_down_o.png", w:48, h:48},
    {name:"rgb", uri:"/assets/raw/images/x2/rgb.png", w:30, h:30},
    {name:"arrow_down_n", uri:"/assets/raw/images/x2/arrow_down_n.png", w:48, h:48},
    {name:"green_btn_o", uri:"/assets/raw/images/x2/green_btn_o.png", w:30, h:30},
    {name:"msg_active", uri:"/assets/raw/images/x2/msg_active.png", w:48, h:48},
    {name:"play_n", uri:"/assets/raw/images/x2/play_n.png", w:48, h:48},
    {name:"radio_checked", uri:"/assets/raw/images/x2/radio_checked.png", w:48, h:48},
    {name:"middle_on", uri:"/assets/raw/images/x2/middle_on.png", w:48, h:48},
    {name:"msg", uri:"/assets/raw/images/x2/msg.png", w:48, h:48},
    {name:"play_o", uri:"/assets/raw/images/x2/play_o.png", w:48, h:48},
    {name:"bricks", uri:"/assets/raw/images/x2/bricks.png", w:60, h:60},
    {name:"shifton", uri:"/assets/raw/images/x2/shifton.png", w:32, h:32},
    {name:"active_dot", uri:"/assets/raw/images/x2/active_dot.png", w:16, h:16},
    {name:"question", uri:"/assets/raw/images/x2/question.png", w:48, h:48},
    {name:"zh", uri:"/assets/raw/images/x2/zh.png", w:48, h:48},
    {name:"discovery_active", uri:"/assets/raw/images/x2/discovery_active.png", w:48, h:48},
    {name:"dot", uri:"/assets/raw/images/x2/dot.png", w:16, h:16},
    {name:"rgba", uri:"/assets/raw/images/x2/rgba.png", w:30, h:30},
    {name:"empty", uri:"/assets/raw/images/x2/empty.png", w:24, h:24},
    {name:"battery_0", uri:"/assets/raw/images/x2/battery_0.png", w:57, h:32},
    {name:"num_0", uri:"/assets/raw/images/x2/num_0.jpg", w:38, h:60},
    {name:"slider_v_fg", uri:"/assets/raw/images/x2/slider_v_fg.png", w:8, h:30},
    {name:"ani1", uri:"/assets/raw/images/x2/ani1.png", w:140, h:140},
    {name:"visible", uri:"/assets/raw/images/x2/visible.png", w:32, h:32},
    {name:"edit_clear_p", uri:"/assets/raw/images/x2/edit_clear_p.png", w:48, h:48},
    {name:"arrow_up_o", uri:"/assets/raw/images/x2/arrow_up_o.png", w:48, h:48},
    {name:"arrow_up_n", uri:"/assets/raw/images/x2/arrow_up_n.png", w:48, h:48},
    {name:"left_on", uri:"/assets/raw/images/x2/left_on.png", w:48, h:48},
    {name:"num_1", uri:"/assets/raw/images/x2/num_1.jpg", w:38, h:60},
    {name:"battery_1", uri:"/assets/raw/images/x2/battery_1.png", w:57, h:32},
    {name:"arrow_right_p", uri:"/assets/raw/images/x2/arrow_right_p.png", w:48, h:48},
    {name:"guage_bg", uri:"/assets/raw/images/x2/guage_bg.png", w:240, h:240},
    {name:"battery_3", uri:"/assets/raw/images/x2/battery_3.png", w:57, h:32},
    {name:"num_3", uri:"/assets/raw/images/x2/num_3.jpg", w:38, h:60},
    {name:"slider_drag_o", uri:"/assets/raw/images/x2/slider_drag_o.png", w:28, h:28},
    {name:"en", uri:"/assets/raw/images/x2/en.png", w:48, h:48},
    {name:"ani2", uri:"/assets/raw/images/x2/ani2.png", w:140, h:140},
    {name:"arrow_left_n", uri:"/assets/raw/images/x2/arrow_left_n.png", w:48, h:48},
    {name:"clock_second", uri:"/assets/raw/images/x2/clock_second.png", w:2, h:180},
    {name:"arrow_left_o", uri:"/assets/raw/images/x2/arrow_left_o.png", w:48, h:48},
    {name:"ani3", uri:"/assets/raw/images/x2/ani3.png", w:140, h:140},
    {name:"num_2", uri:"/assets/raw/images/x2/num_2.jpg", w:38, h:60},
    {name:"battery_2", uri:"/assets/raw/images/x2/battery_2.png", w:57, h:32},
    {name:"num_6", uri:"/assets/raw/images/x2/num_6.jpg", w:38, h:60},
    {name:"ania", uri:"/assets/raw/images/x2/ania.png", w:140, h:140},
    {name:"ani7", uri:"/assets/raw/images/x2/ani7.png", w:140, h:140},
    {name:"shift", uri:"/assets/raw/images/x2/shift.png", w:32, h:32},
    {name:"ani6", uri:"/assets/raw/images/x2/ani6.png", w:140, h:140},
    {name:"close_p", uri:"/assets/raw/images/x2/close_p.png", w:48, h:48},
    {name:"num_7", uri:"/assets/raw/images/x2/num_7.jpg", w:38, h:60},
    {name:"checked", uri:"/assets/raw/images/x2/checked.png", w:48, h:48},
    {name:"battery_5", uri:"/assets/raw/images/x2/battery_5.png", w:57, h:32},
    {name:"num_5", uri:"/assets/raw/images/x2/num_5.jpg", w:38, h:60},
    {name:"anib", uri:"/assets/raw/images/x2/anib.png", w:140, h:140},
    {name:"ani4", uri:"/assets/raw/images/x2/ani4.png", w:140, h:140},
    {name:"me_active", uri:"/assets/raw/images/x2/me_active.png", w:48, h:48},
    {name:"ani5", uri:"/assets/raw/images/x2/ani5.png", w:140, h:140},
    {name:"anic", uri:"/assets/raw/images/x2/anic.png", w:140, h:140},
    {name:"earth", uri:"/assets/raw/images/x2/earth.png", w:48, h:48},
    {name:"contact_active", uri:"/assets/raw/images/x2/contact_active.png", w:48, h:48},
    {name:"dialog_title", uri:"/assets/raw/images/x2/dialog_title.png", w:60, h:30},
    {name:"num_4", uri:"/assets/raw/images/x2/num_4.jpg", w:38, h:60},
    {name:"close_d", uri:"/assets/raw/images/x2/close_d.png", w:48, h:48},
    {name:"battery_4", uri:"/assets/raw/images/x2/battery_4.png", w:57, h:32},
    {name:"contact", uri:"/assets/raw/images/x2/contact.png", w:48, h:48},
    {name:"slider_fg", uri:"/assets/raw/images/x2/slider_fg.png", w:30, h:8},
    {name:"arrow_right_o", uri:"/assets/raw/images/x2/arrow_right_o.png", w:48, h:48},
    {name:"num_9", uri:"/assets/raw/images/x2/num_9.jpg", w:38, h:60},
    {name:"ani8", uri:"/assets/raw/images/x2/ani8.png", w:140, h:140},
    {name:"edit_clear_n", uri:"/assets/raw/images/x2/edit_clear_n.png", w:48, h:48},
    {name:"arrow_up_p", uri:"/assets/raw/images/x2/arrow_up_p.png", w:48, h:48},
    {name:"edit_clear_o", uri:"/assets/raw/images/x2/edit_clear_o.png", w:48, h:48},
    {name:"ani9", uri:"/assets/raw/images/x2/ani9.png", w:140, h:140},
    {name:"find", uri:"/assets/raw/images/x2/find.png", w:48, h:48},
    {name:"discovery", uri:"/assets/raw/images/x2/discovery.png", w:48, h:48},
    {name:"num_8", uri:"/assets/raw/images/x2/num_8.jpg", w:38, h:60},
    {name:"arrow_right_n", uri:"/assets/raw/images/x2/arrow_right_n.png", w:48, h:48},
    {name:"backspace", uri:"/assets/raw/images/x2/backspace.png", w:32, h:32},
    {name:"arrow_left_p", uri:"/assets/raw/images/x2/arrow_left_p.png", w:48, h:48},
    {name:"clock_hour", uri:"/assets/raw/images/x2/clock_hour.png", w:20, h:82},
    {name:"slider_drag_p", uri:"/assets/raw/images/x2/slider_drag_p.png", w:28, h:28},
    {name:"logo", uri:"/assets/raw/images/x2/logo.png", w:148, h:68},
    {name:"invisible", uri:"/assets/raw/images/x2/invisible.png", w:32, h:32},
    {name:"close_o", uri:"/assets/raw/images/x2/close_o.png", w:48, h:48},
    {name:"clock_bg", uri:"/assets/raw/images/x2/clock_bg.jpg", w:300, h:300},
    {name:"cross", uri:"/assets/raw/images/x2/cross.png", w:64, h:64},
    {name:"clock_minute", uri:"/assets/raw/images/x2/clock_minute.png", w:12, h:135},
    {name:"radio_unchecked", uri:"/assets/raw/images/x2/radio_unchecked.png", w:48, h:48},
    {name:"switch", uri:"/assets/raw/images/x2/switch.png", w:180, h:45},
    {name:"close_n", uri:"/assets/raw/images/x2/close_n.png", w:48, h:48},
    {name:"clock", uri:"/assets/raw/images/x2/clock.png", w:42, h:42},
    {name:"unchecked", uri:"/assets/raw/images/x2/unchecked.png", w:48, h:48},
    {name:"red_btn_n", uri:"/assets/raw/images/x2/red_btn_n.png", w:30, h:30},
    {name:"slider_drag", uri:"/assets/raw/images/x2/slider_drag.png", w:28, h:28},
    {name:"red_btn_o", uri:"/assets/raw/images/x2/red_btn_o.png", w:30, h:30},
    {name:"green_btn_p", uri:"/assets/raw/images/x2/green_btn_p.png", w:30, h:30},
    {name:"arrow_down_p", uri:"/assets/raw/images/x2/arrow_down_p.png", w:48, h:48},
    {name:"warn", uri:"/assets/raw/images/x2/warn.png", w:48, h:48},
    {name:"slider_v_bg", uri:"/assets/raw/images/x2/slider_v_bg.png", w:8, h:30},
    {name:"right_on", uri:"/assets/raw/images/x2/right_on.png", w:48, h:48},
    {name:"2", uri:"/assets/raw/images/x2/2.jpg", w:200, h:146},
    {name:"slider_bg", uri:"/assets/raw/images/x2/slider_bg.png", w:30, h:8},
    {name:"guage_pointer", uri:"/assets/raw/images/x2/guage_pointer.png", w:24, h:144},
    {name:"play_p", uri:"/assets/raw/images/x2/play_p.png", w:48, h:48},
    {name:"unmuted", uri:"/assets/raw/images/x2/unmuted.png", w:48, h:48},
    {name:"right_off", uri:"/assets/raw/images/x2/right_off.png", w:48, h:48},
    {name:"message", uri:"/assets/raw/images/x2/message.png", w:64, h:64},
    {name:"3", uri:"/assets/raw/images/x2/3.jpg", w:200, h:146},
    {name:"1", uri:"/assets/raw/images/x2/1.jpg", w:128, h:128},
    {name:"progress_circle", uri:"/assets/raw/images/x2/progress_circle.png", w:100, h:100},
    {name:"bee", uri:"/assets/raw/images/x2/bee.gif", w:80, h:80},
    {name:"left_off", uri:"/assets/raw/images/x2/left_off.png", w:48, h:48},
  ],
  ui: [
    {name:"label", uri:"/assets/raw/ui/label.bin"},
    {name:"image_value", uri:"/assets/raw/ui/image_value.bin"},
    {name:"system_bar", uri:"/assets/raw/ui/system_bar.bin"},
    {name:"auto_play_landscape", uri:"/assets/raw/ui/auto_play_landscape.bin"},
    {name:"auto_play_portrait", uri:"/assets/raw/ui/auto_play_portrait.bin"},
    {name:"kb_ufloat", uri:"/assets/raw/ui/kb_ufloat.bin"},
    {name:"animation", uri:"/assets/raw/ui/animation.bin"},
    {name:"bottom", uri:"/assets/raw/ui/bottom.bin"},
    {name:"list_view", uri:"/assets/raw/ui/list_view.bin"},
    {name:"tab_bottom_compact", uri:"/assets/raw/ui/tab_bottom_compact.bin"},
    {name:"kb_default", uri:"/assets/raw/ui/kb_default.bin"},
    {name:"kb_int", uri:"/assets/raw/ui/kb_int.bin"},
    {name:"scroll_view_h", uri:"/assets/raw/ui/scroll_view_h.bin"},
    {name:"tab_list", uri:"/assets/raw/ui/tab_list.bin"},
    {name:"kb_ascii", uri:"/assets/raw/ui/kb_ascii.bin"},
    {name:"guage", uri:"/assets/raw/ui/guage.bin"},
    {name:"image_animation", uri:"/assets/raw/ui/image_animation.bin"},
    {name:"slide_view_h", uri:"/assets/raw/ui/slide_view_h.bin"},
    {name:"kb_phone", uri:"/assets/raw/ui/kb_phone.bin"},
    {name:"auto_play", uri:"/assets/raw/ui/auto_play.bin"},
    {name:"animator", uri:"/assets/raw/ui/animator.bin"},
    {name:"memtest", uri:"/assets/raw/ui/memtest.bin"},
    {name:"scroll_view", uri:"/assets/raw/ui/scroll_view.bin"},
    {name:"list_view_m", uri:"/assets/raw/ui/list_view_m.bin"},
    {name:"lua", uri:"/assets/raw/ui/lua.bin"},
    {name:"tab_top_compact", uri:"/assets/raw/ui/tab_top_compact.bin"},
    {name:"fade", uri:"/assets/raw/ui/fade.bin"},
    {name:"scroll_bar_h", uri:"/assets/raw/ui/scroll_bar_h.bin"},
    {name:"vtranslate", uri:"/assets/raw/ui/vtranslate.bin"},
    {name:"calibration_win", uri:"/assets/raw/ui/calibration_win.bin"},
    {name:"digit_clock", uri:"/assets/raw/ui/digit_clock.bin"},
    {name:"text_selector", uri:"/assets/raw/ui/text_selector.bin"},
    {name:"tab_bottom", uri:"/assets/raw/ui/tab_bottom.bin"},
    {name:"list_view_vh", uri:"/assets/raw/ui/list_view_vh.bin"},
    {name:"selectm", uri:"/assets/raw/ui/selectm.bin"},
    {name:"color_picker_full", uri:"/assets/raw/ui/color_picker_full.bin"},
    {name:"htranslate", uri:"/assets/raw/ui/htranslate.bin"},
    {name:"rich_text1", uri:"/assets/raw/ui/rich_text1.bin"},
    {name:"list_view_h", uri:"/assets/raw/ui/list_view_h.bin"},
    {name:"keyboard", uri:"/assets/raw/ui/keyboard.bin"},
    {name:"rich_text2", uri:"/assets/raw/ui/rich_text2.bin"},
    {name:"main", uri:"/assets/raw/ui/main.bin"},
    {name:"list_view_d", uri:"/assets/raw/ui/list_view_d.bin"},
    {name:"tab_control", uri:"/assets/raw/ui/tab_control.bin"},
    {name:"edit", uri:"/assets/raw/ui/edit.bin"},
    {name:"gif_image", uri:"/assets/raw/ui/gif_image.bin"},
    {name:"vgcanvas", uri:"/assets/raw/ui/vgcanvas.bin"},
    {name:"soft_keyboard", uri:"/assets/raw/ui/soft_keyboard.bin"},
    {name:"slide_view_h1", uri:"/assets/raw/ui/slide_view_h1.bin"},
    {name:"locale", uri:"/assets/raw/ui/locale.bin"},
    {name:"svg_image", uri:"/assets/raw/ui/svg_image.bin"},
    {name:"basic", uri:"/assets/raw/ui/basic.bin"},
    {name:"linear_gradient", uri:"/assets/raw/ui/linear_gradient.bin"},
    {name:"rich_text", uri:"/assets/raw/ui/rich_text.bin"},
    {name:"color_picker", uri:"/assets/raw/ui/color_picker.bin"},
    {name:"combo_box", uri:"/assets/raw/ui/combo_box.bin"},
    {name:"slide_view_h2", uri:"/assets/raw/ui/slide_view_h2.bin"},
    {name:"color_picker_rgb", uri:"/assets/raw/ui/color_picker_rgb.bin"},
    {name:"button", uri:"/assets/raw/ui/button.bin"},
    {name:"select1", uri:"/assets/raw/ui/select1.bin"},
    {name:"image_list", uri:"/assets/raw/ui/image_list.bin"},
    {name:"progress_circle", uri:"/assets/raw/ui/progress_circle.bin"},
    {name:"images", uri:"/assets/raw/ui/images.bin"},
    {name:"stroke_gradient", uri:"/assets/raw/ui/stroke_gradient.bin"},
    {name:"slide_view_v2", uri:"/assets/raw/ui/slide_view_v2.bin"},
    {name:"kb_float", uri:"/assets/raw/ui/kb_float.bin"},
    {name:"big_font", uri:"/assets/raw/ui/big_font.bin"},
    {name:"top", uri:"/assets/raw/ui/top.bin"},
    {name:"color_picker_hsv", uri:"/assets/raw/ui/color_picker_hsv.bin"},
    {name:"scroll_bar", uri:"/assets/raw/ui/scroll_bar.bin"},
    {name:"slide_view", uri:"/assets/raw/ui/slide_view.bin"},
    {name:"slide_view_h_loop", uri:"/assets/raw/ui/slide_view_h_loop.bin"},
    {name:"dialog1", uri:"/assets/raw/ui/dialog1.bin"},
    {name:"slide_view_v1", uri:"/assets/raw/ui/slide_view_v1.bin"},
    {name:"dialog2", uri:"/assets/raw/ui/dialog2.bin"},
    {name:"dialogs", uri:"/assets/raw/ui/dialogs.bin"},
    {name:"switch", uri:"/assets/raw/ui/switch.bin"},
    {name:"preload", uri:"/assets/raw/ui/preload.bin"},
    {name:"tab_top", uri:"/assets/raw/ui/tab_top.bin"},
    {name:"color", uri:"/assets/raw/ui/color.bin"},
    {name:"color_picker_simple", uri:"/assets/raw/ui/color_picker_simple.bin"},
    {name:"spinbox", uri:"/assets/raw/ui/spinbox.bin"},
    {name:"radial_gradient", uri:"/assets/raw/ui/radial_gradient.bin"},
    {name:"scroll_view_v", uri:"/assets/raw/ui/scroll_view_v.bin"},
    {name:"slide_view_v_loop", uri:"/assets/raw/ui/slide_view_v_loop.bin"},
    {name:"kb_uint", uri:"/assets/raw/ui/kb_uint.bin"},
    {name:"time_clock", uri:"/assets/raw/ui/time_clock.bin"},
    {name:"kb_hex", uri:"/assets/raw/ui/kb_hex.bin"},
    {name:"slide_menu", uri:"/assets/raw/ui/slide_menu.bin"},
    {name:"dragger", uri:"/assets/raw/ui/dragger.bin"},
    {name:"language", uri:"/assets/raw/ui/language.bin"},
    {name:"slide_view_v", uri:"/assets/raw/ui/slide_view_v.bin"},
  ],
  style: [
    {name:"system_bar", uri:"/assets/raw/styles/system_bar.bin"},
    {name:"dialog_confirm", uri:"/assets/raw/styles/dialog_confirm.bin"},
    {name:"tab_bottom_compact", uri:"/assets/raw/styles/tab_bottom_compact.bin"},
    {name:"dialog_info", uri:"/assets/raw/styles/dialog_info.bin"},
    {name:"tab_list", uri:"/assets/raw/styles/tab_list.bin"},
    {name:"guage", uri:"/assets/raw/styles/guage.bin"},
    {name:"tab_top_compact", uri:"/assets/raw/styles/tab_top_compact.bin"},
    {name:"digit_clock", uri:"/assets/raw/styles/digit_clock.bin"},
    {name:"tab_bottom", uri:"/assets/raw/styles/tab_bottom.bin"},
    {name:"keyboard", uri:"/assets/raw/styles/keyboard.bin"},
    {name:"edit", uri:"/assets/raw/styles/edit.bin"},
    {name:"default", uri:"/assets/raw/styles/default.bin"},
    {name:"button", uri:"/assets/raw/styles/button.bin"},
    {name:"calibration", uri:"/assets/raw/styles/calibration.bin"},
    {name:"big_font", uri:"/assets/raw/styles/big_font.bin"},
    {name:"dialog", uri:"/assets/raw/styles/dialog.bin"},
    {name:"dialog_toast", uri:"/assets/raw/styles/dialog_toast.bin"},
    {name:"tab_top", uri:"/assets/raw/styles/tab_top.bin"},
    {name:"dialog_warn", uri:"/assets/raw/styles/dialog_warn.bin"},
    {name:"color", uri:"/assets/raw/styles/color.bin"},
    {name:"slide_menu", uri:"/assets/raw/styles/slide_menu.bin"},
  ],
  string: [
    {name:"zh_CN", uri:"/assets/raw/strings/zh_CN.bin"},
    {name:"en_US", uri:"/assets/raw/strings/en_US.bin"},
  ],
  xml: [
    {name:"test", uri:"/assets/raw/xml/test.xml"},
  ],
  data: [
    {name:"test", uri:"/assets/raw/data/test.json"},
    {name:"com.zlg.app", uri:"/assets/raw/data/com.zlg.app.json"},
    {name:"a-b-c", uri:"/assets/raw/data/a-b-c.any"},
    {name:"test", uri:"/assets/raw/data/test.dat"},
  ],
  script: [
    {name:"dummy", uri:"/assets/raw/scripts/dummy.js"},
  ],
  font: [
    {name:"default", uri:"/assets/raw/fonts/default.ttf"},
    {name:"default.mini", uri:"/assets/raw/fonts/default.mini.ttf"},
    {name:"ap", uri:"/assets/raw/fonts/ap.ttf"},
  ],
};