import os
import sys
import platform

env = DefaultEnvironment().Clone()
BIN_DIR = os.environ['BIN_DIR']
LIB_DIR = os.environ['LIB_DIR'];

sources = Glob('**/*.c') + Glob('*.c')

env.Program(os.path.join(BIN_DIR, 'demo'), sources, LIBS = env['LIBS'])
